# See https://docs.travis-ci.com/user/languages/r/
language: r
r:
  - oldrel
  - release
  - devel
cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  - Rscript -e 'devtools::install_github("gitter-lab/LPWC")'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
    condition: "$TRAVIS_R_VERSION_STRING = release"

notifications:
  email: false

# Will fail with WARNINGS from R CMD check.  Uncomment to ignore WARNINGS.
# warnings_are_errors: false
